# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: de65dd9ce30a7f68bb2751a529200ded9ff519bcd56dd2ac09bb5134222ca44b03534b52ce4fae4205026282ccb7276dbe031b97c444a9ff4efbf50c4bfcb65b

test:
  secret_key_base: 6ab7a4b505b154c1f7b6f63a86f2150559a9c6ba5eecc1acec65090f0ada8a25711319623689ac6a36b10ed714172c09685a14533116b0e9a2ec049d9fa81be8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
